[tool.black]
skip-string-normalization = false
line-length = 120
target-version = ['py39', 'py310', 'py311', 'py312']
extend-exclude = '''
/(
  | plugins/module_utils/_version.py
)/
'''

[tool.isort]
profile = "black"
line_length = 120

src_paths = [
    "plugins",
    "tests/unit",
    "tests/integration",
]
